name: Build docs on PR
on: pull_request
jobs:
  build-and-preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Requirements
        run: apt-get install doxygen
          && apt install python3-pip
          && apt-get install python3-sphinx
          && pip3 install sphinx-rtd-theme
          && pip3 install breathe
          && pip3 install sphinx-sitemap
      - name: Build docs
        uses: actions/checkout@v2
        run: cd docs_sphinx
          && make html
          && cd _build/html
          && touch .nojekyll
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOXYGEN_TEST }}'
          projectId: doxygen-test
          expires: 7d

